runtime: python310

entrypoint: gunicorn maximus_web.wsgi:application

env_variables:
  # Replace with your actual API key or set it in Google Cloud Console
  OPENAI_API_KEY: "your-openai-key-here"
  DJANGO_SETTINGS_MODULE: "maximus_web.settings"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto